In [6]:
import pandas as pd

df=pd.read_csv('winequality-red.csv')
df

     fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
0      7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5
1      7.8;0.88;0;2.6;0.098;25;67;0.9968;3.2;0.68;9.8;5
2     7.8;0.76;0.04;2.3;0.092;15;54;0.997;3.26;0.65;...
3     11.2;0.28;0.56;1.9;0.075;17;60;0.998;3.16;0.58...
4      7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5
...                                                 ...
1594  6.2;0.6;0.08;2;0.09;32;44;0.9949;3.45;0.58;10.5;5
1595  5.9;0.55;0.1;2.2;0.062;39;51;0.99512;3.52;0.76...
1596  6.3;0.51;0.13;2.3;0.076;29;40;0.99574;3.42;0.7...
1597  5.9;0.645;0.12;2;0.075;32;44;0.99547;3.57;0.71...
1598  6;0.31;0.47;3.6;0.067;18;42;0.99549;3.39;0.66;...

[1599 rows x 1 columns]

In [7]:
df.describe()

       fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
count                                                1599
unique                                               1359
top     7.5;0.51;0.02;1.7;0.084;13;31;0.99538;3.36;0.5...
freq                                                    4

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 1 columns):
 #   Column                                                                                                                                                                   Non-Null Count  Dtype
---  ------                                                                                                                                                                   --------------  -----
 0   fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"  1599 non-null   object
dtypes: object(1)
memory usage: 12.6+ KB