In [1]:
import pandas as pd

## series- an array like object
## data frame is a tablular two dimentional size mutable and hetrogeneous tabular data structure with labled axes

In [4]:
## series

data= [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
## series from dectionary
data = {'a':1 , 'b': 2 , "c":3}
pd.Series(data)
## key becomes the indx and value becomes the data

a    1
b    2
c    3
dtype: int64

In [6]:
data=[10,20,30,40,45]
index=['a','b','c','d','e']
pd.Series(data,index=index)

a    10
b    20
c    30
d    40
e    45
dtype: int64

In [ ]:
##dataframe
## creating from dectionary

data= {'name':['vani' , 'dev' , 'anupam'],
       'age':[20,29,34],
       'city':['delhi' , 'mumbai' , ' meerut']}

print(data)

Df=pd.DataFrame(data)
print(Df)
index = index=['a','b','c']

{'name': ['vani', 'dev', 'anupam'], 'age': [20, 29, 34], 'city': ['delhi', 'mumbai', ' meerut']}
     name  age     city
0    vani   20    delhi
1     dev   29   mumbai
2  anupam   34   meerut

In [11]:
index = index=['a','b','c']
Df=pd.DataFrame(data , index=index)
print(Df)

     name  age     city
a    vani   20    delhi
b     dev   29   mumbai
c  anupam   34   meerut

In [13]:
import numpy as np
np.array(Df)

array([['vani', 20, 'delhi'],
       ['dev', 29, 'mumbai'],
       ['anupam', 34, ' meerut']], dtype=object)

In [ ]:
data = [
    {'name':['vani' , 'dev' , 'anupam'],
       'age':[20,29,34],
       'city':['delhi' , 'mumbai' , ' meerut']}
       ]

In [17]:
df=pd.read_csv('people-100.csv')

In [19]:
df.head(5)

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon

In [20]:
df.tail(10)

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
90,91,F0aeC9c2759F3C6,Alison,Nixon,Female,zmiles@example.net,3506680871,1941-07-10,Patent attorney
91,92,d6EA619A7C4aA95,Jamie,Hardy,Female,sheenadouglas@example.com,(900)803-9295x11533,1994-07-17,"Conservator, furniture"
92,93,2A33E7Cad1bb0F5,Melody,Cox,Female,evan90@example.org,(626)520-5080x3511,1974-07-30,Dance movement psychotherapist
93,94,d181FFB7d3E68bb,Xavier,Cole,Male,nicolas90@example.org,8164259975,1938-11-29,Financial planner
94,95,feaBf8dAE0C0d6F,Dillon,Guzman,Female,angelanavarro@example.net,971-992-4521,1942-04-01,Air broker
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,1954-07-30,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,1932-04-29,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,1994-12-28,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,2012-04-12,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,2016-11-15,IT sales professional

In [23]:
##acessing the dats from df

df['Index']
type(df['Index'])

pandas.core.series.Series

In [ ]:
df.loc[0]
##ill give 0th row

Index                                 1
User Id                 88F7B33d2bcf9f5
First Name                       Shelby
Last Name                       Terrell
Sex                                Male
Email              elijah57@example.net
Phone            001-084-906-7849x73518
Date of birth                1945-10-26
Job Title               Games developer
Name: 0, dtype: object

In [26]:
df.loc[0][2]

C:\Users\chaud\AppData\Local\Temp\ipykernel_33040\2880214942.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][2]

'Shelby'